# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'SwiftProjectScaffold' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChongYaProjectScaffold
  pod 'Parchment', '3.0.1'
  pod 'TZImagePickerController', '3.6.6'
  pod 'RxCocoa', '6.2.0'
  pod 'IQKeyboardManagerSwift', '6.5.8'
  pod 'SnapKit', '5.0.1'
  pod 'SPPermissions/Camera'
  pod 'SPPermissions/LocationAlways'
  
  pod 'RxSwift', '6.2.0'
  pod 'HandyJSON', '5.0.4-beta'
  pod 'Moya/RxSwift', '15.0.0'
  
  pod 'R.swift', '5.4.0'
  pod 'Hue', '5.0.0'
  pod 'SDWebImage', '5.12.0'
  
  pod 'SwiftyRSA', '1.7.0'
  pod 'CryptoSwift', '1.4.2' # 常用对称加密算法和摘要算法
  pod 'PhoneNumberKit', '3.3.3'
  
#  友盟
  pod 'UMCommon', '7.3.5'
  pod 'UMDevice', '2.0.5'
  pod 'UMAPM', '1.4.2'
  pod 'UMCCommonLog', '2.0.2', :configurations => ['Debug']
  
# 调试相关
  pod 'YKWoodpecker', '1.2.9'
  pod 'CocoaLumberjack/Swift', '3.7.2'
  pod 'SwiftLint', '0.45.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # https://github.com/CocoaPods/CocoaPods/issues/9884
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
